# app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.proxy.name }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.proxy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.proxy.name }}
    spec:
      containers:
      - name: proxy-server-container
        image: {{ .Values.proxy.image_name }}
        ports:
        - containerPort: {{ .Values.proxy.containerPort }}
