# app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-server
  template:
    metadata:
      labels:
        app: proxy-server
    spec:
      containers:
      - name: proxy-server-container
        image: bsubash2054/nginx-reverse-proxy
        ports:
        - containerPort: 80
