db:
  name: wp-database
  labels:
    id: c0927502
    app: db
    env: dev
    stack: wordpress
  image:
    repository: mariadb
    tag: 10.6.4-focal
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: c0927502
    MYSQL_USER: 3324_user
    APP_ENV: dev
  containerPorts:
      mysql: 3306
