wp:
  name: wpapp
  labels:
    id: c0927502
    app: wp
    env: dev
    stack: wordpress
  image:
    repository: wordpress
    tag: latest
    pullPolicy: Always
  replicas: 10
  configmap:
    ## KEY: "value"
    APP_ENV: dev
    WORDPRESS_DB_HOST: wp-database.db.svc.cluster.local
    WORDPRESS_DB_NAME: c0927502
    WORDPRESS_DB_USER: 3324_user
  containerPorts:
      http: 80
